// ---- AUTOGENERATED, DONT CHANGE THIS BY HAND ----
export const loginCodeV3 = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
	<!--[if gte mso 9]>
	<xml>
		<o:OfficeDocumentSettings>
		<o:AllowPNG/>
		<o:PixelsPerInch>96</o:PixelsPerInch>
		</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="format-detection" content="date=no">
	<meta name="format-detection" content="address=no">
	<meta name="format-detection" content="telephone=no">
	

	<title>OCH</title>
	

	
</head>
<body class="body" style="-webkit-text-size-adjust: none; background: #f3f3f3; display: block !important; margin: 0 !important; min-width: 100% !important; padding: 0 !important; width: 100% !important;">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f3f3f3">
		<tr>
			<td align="center" valign="top">
				<table width="650" border="0" cellspacing="0" cellpadding="0" class="mobile-shell" style="margin-top: 41px;">
					<tr>
						<td class="td" style="width:650px;min-width:650px;font-size:0pt;line-height:0pt;/* padding:30px 0px 30px 0px; */margin:0;font-weight:normal;Margin:0;background: white;border-radius: 20px;box-shadow: 2px 2px 30px #0000003d;">

							<table width="100%" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td class="section3" style="padding: 30px 0px 10px 0px;">
										<table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<th class="column-top" style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top; Margin:0" width="172">
													<table width="100%" border="0" cellspacing="0" cellpadding="0">
														<tr>
															<td class="img" style="font-size:0pt; line-height:0pt; text-align:center"><div class="img-m-center" style="font-size:0pt; line-height:0pt"><a href="https://OCH.io/" target="_blank" style="color: #acacac; text-decoration: none;"><img style="-ms-interpolation-mode: bicubic; filter: drop-shadow(rgba(0, 0, 0, .4) 0 2px 9px);" src="https://OCH.io/assets/img/root/logo.png" border="0" width="300" alt></a></div></td>
														</tr>
													</table>
												</th>
											</tr>
										</table>
									</td>
								</tr>
							</table>
							
							<!-- Section 1 -->
							<table width="100%" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td class="section" style="padding:30px 0px 10px 0px">
										<table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<td class="separator1" style="padding: 0px 30px 30px 30px;"><table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#e3e3e3" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%"><tr><td bgcolor="#e3e3e3" height="1" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%">&nbsp;</td></tr></table></td>
											</tr>
											<tr>
												<td style="color: #000000; font-family: 'Muli', Georgia, serif !important; font-size: 20px; font-weight: bold; line-height: 34px; padding-left: 30px;">This is your OCH login code:<div style="font-size:0pt; line-height:0pt;" class="mobile-br-15"></div></td>
											</tr>
											<tr>
												<td class="h2-center" style="color: #000000; font-family: 'Muli', Georgia, serif !important; font-size: 30px; font-weight: bold; line-height: 34px; text-align: center;"><pre style="border: 2px solid #f3cd68; border-radius: 9px; box-shadow: 6px 5px 0px 0px rgb(239 201 110); font-family: 'Muli', Georgia, serif !important; font-size: 25px; margin: 55px auto 35px auto; padding: 8px; width: 45%;">%CODE%</pre><div style="font-size:0pt; line-height:0pt;" class="mobile-br-15"></div></td>
											</tr>
											<tr>
												<td style="color: #000000; font-family: 'Muli', Georgia, serif !important; font-size: 13px; line-height: 20px; padding: 30px 30px 0px 30px;">If you did not make this login attempt you should create a support ticket immediately.</td>
											</tr>
											<tr>
												<td class="pb20" style="padding-bottom:20px"></td>
											</tr>
							
										</table>
									</td>
								</tr>
							</table>
							<!-- END Section 1 -->
							<!-- Section 5 -->
							<table width="100%" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td>
										<table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<td class="separator1" style="padding: 30px 30px 30px; 0px"><table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#e3e3e3" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%"><tr><td bgcolor="#e3e3e3" height="1" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%">&nbsp;</td></tr></table></td>
											</tr>
											<tr>
												<td style="color: #000000; font-family: 'Muli', Georgia, serif !important; font-size: 13px; line-height: 1.5; padding: 30px;">Greetings and success from the OCH team. <br> This notification has been sent because you have signed up on OCH. </td>
											</tr>
											<tr>
												<td class="separator1" style="padding:0px 30px 0px 30px"><table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#e3e3e3" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%"><tr><td bgcolor="#e3e3e3" height="1" class="border" style="font-size:0pt; line-height:0pt; text-align:center; width:100%; min-width:100%">&nbsp;</td></tr></table></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
							<!-- END Section 5 -->

							<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background: #efc96e; border-radius: 15px 0 15px 0;">
								<tr>
									<td style="padding: 30px">
										<multiline class="text-footer-c" style="color: #ffff; font-family: 'Muli', Arial, sans-serif !important; font-size: 11px; line-height: 16px; text-align: center;">www.OCH.io</multiline>
									</td>
									<td style="padding: 30px" align="right">
										<div style="font-size:0pt; line-height:0pt;" class="mobile-br-15"></div>

										<table class="center" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<td class="img" style="font-size:0pt; line-height:0pt; text-align:left" width="32"><a href="https://discord.gg/OCH" target="_blank" style="color: #acacac; text-decoration: none;"><img style="-ms-interpolation-mode: bicubic; background: white; border-radius: 5px; padding: 5px;" src="https://OCH.io/assets/email/images/ico_discord.png" border="0" width="16" height="14" alt></a></td>
												<td class="img" style="font-size:0pt; line-height:0pt; text-align:left" width="32"><a href="https://twitter.com/OCHnft" target="_blank" style="color: #acacac; text-decoration: none;"><img style="-ms-interpolation-mode: bicubic; background: white; border-radius: 5px; padding: 5px;" src="https://OCH.io/assets/email/images/ico_twitter.jpg" border="0" width="16" height="14" alt></a></td>
												<td class="img" style="font-size:0pt; line-height:0pt; text-align:left" width="16"><a href="https://www.instagram.com/OCHnft/" target="_blank" style="color: #acacac; text-decoration: none;"><img style="-ms-interpolation-mode: bicubic; background: white; border-radius: 5px; padding: 5px;" src="https://OCH.io/assets/email/images/ico_instagram.jpg" border="0" width="16" height="14" alt></a></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
							<!-- END Footer -->
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
<!-- Code injected by live-server -->
<script type="text/javascript">
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function () {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					var parent = elem.parentElement || head;
					parent.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					parent.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function (msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
				console.log('Live reload enabled.');
				sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
			}
		})();
	}
	else {
		console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}
	// ]]>
</script></body>
</html>
`;
