version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass wuYZ5b9WzeCs
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:4.4.6
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
